
@extends('biowell.index')

@section('biowell-contenido')
    <h3 style="color: orange">{{$titulo2}}</h3>
    <p>Bio-Well es una herramienta revolucionaria basada en la técnica de imágenes electrofónicas o de visualización de descargas de gases (efecto Kirlian), hecha especialmente para la evaluación expresa del estado funcional o energético de una persona. La interpretación de las exploraciones se basa en la medicina tradicional china (MTC), Auyrveda y muchas investigaciones científicas y clínicas realizadas a lo largo de 20 años. Permite prever los trastornos funcionales y tomar acciones preventivas antes de que se produzca la enfermedad. Es rápido, visual y fácil de usar.</p>
    <p>Bio-Well ha sido desarrollado por un equipo internacional dirigido por el Dr. Konstantin Korotkov y trae al mercado la poderosa tecnología conocida como técnica de visualización de descarga de gas de una manera más accesible que nunca. El producto consta de una cámara de escritorio y el software que lo acompaña. Los accesorios adjuntos también están disponibles para la compra para realizar exploraciones de Medio ambiente y BioClip.</p>
    <h4 style="color: orange">La Tecnología: Técnica GDV</h4>
    <p>La técnica GDV es el registro y análisis por computadora de las emisiones electrofotónicas de diferentes objetos, incluidos los biológicos (específicamente los dedos humanos) que resultan de colocar el objeto en el campo electromagnético de alta intensidad en la lente del dispositivo.</p>
    <p>Cuando se realiza una exploración, se aplica una corriente eléctrica débil a las yemas de los dedos durante menos de un milisegundo. La respuesta del objeto a este estímulo es la formación de una variación de una "nube de electrones" compuesta de fotones de energía luminosa. El "resplandor" electrónico de esta descarga, es capturado por el sistema de la cámara y luego traducido y transmitido de nuevo en representaciones gráficas para mostrar las evaluaciones de estrés.</p>
    <p>La imagen, que creamos en el instrumento Bio-Well, se basa en ideas de la medicina tradicional china y se verifica en 20 años de experiencia clínica por cientos de profesionales con miles de pacientes. El proceso de escaneo es rápido, fácil y no intrusivo ... ¡hazlo diariamente para obtener los mejores resultados! Obtenga retroalimentación en tiempo real sobre qué factores, positivos y negativos, afectan su estado de estrés. ¡Con el accesorio Bio-Well Sputnik, mida el medio ambiente y las energías de los objetos también! Bio-Well no es un instrumento médico. Proporciona una impresión de sus niveles de energía y estrés y les permite a los usuarios ver su transformación diaria y la influencia de diferentes situaciones y estímulos. El software amigable hace que el procesamiento de datos sea simple y conveniente para usuarios no experimentados.</p>
@endsection

